### ISSUE TITLE
Compilation error for IonoModbusRtuSlave.h

### ISSUE THREAD

**Issue by BPJWES** [sfera-labs/iono#2]
I am not able to compile neither SimpleRtuSlave.ino nor ModbusRtuApp.ino.

I am following the instructions provided here: https://github.com/sfera-labs/iono/wiki

It seems to me that there is either an incorrect include in IonoModbusRtuSlave.h, or the linked file is missing in the library.

I am using windows 8.1 and am running the Arduino 1.8.6 library. 

The IDE returns the following error:

Arduino:1.8.6 (Windows 8.1), Board:"Arduino/Genuino Uno"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\berjan\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10806 -build-path C:\Users\berjan\AppData\Local\Temp\arduino_build_251274 -warnings=all -build-cache C:\Users\berjan\AppData\Local\Temp\arduino_cache_205903 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\berjan\Dropbox\Electronica\VoorraadRooierMultisepController\TEST_CODE\TEST_CODE.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\berjan\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10806 -build-path C:\Users\berjan\AppData\Local\Temp\arduino_build_251274 -warnings=all -build-cache C:\Users\berjan\AppData\Local\Temp\arduino_cache_205903 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc.path=C:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\berjan\Dropbox\Electronica\VoorraadRooierMultisepController\TEST_CODE\TEST_CODE.ino
Using board 'uno' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Using core 'arduino' from platform in folder: C:\Program Files (x86)\Arduino\hardware\arduino\avr
Detecting libraries used...
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10806 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\berjan\\AppData\\Local\\Temp\\arduino_build_251274\\sketch\\TEST_CODE.ino.cpp" -o nul
"C:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10806 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-IC:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "-IC:\\Users\\berjan\\Documents\\Arduino\\libraries\\IonoModbusRtu" "C:\\Users\\berjan\\AppData\\Local\\Temp\\arduino_build_251274\\sketch\\TEST_CODE.ino.cpp" -o nul
In file included from C:\Users\berjan\Dropbox\Electronica\VoorraadRooierMultisepController\TEST_CODE\TEST_CODE.ino:14:0:

C:\Users\berjan\Documents\Arduino\libraries\IonoModbusRtu/IonoModbusRtuSlave.h:19:28: fatal error: ModbusRtuSlave.h: No such file or directory

compilation terminated.

Bibliotheek IonoModbusRtu in map: C:\Users\berjan\Documents\Arduino\libraries\IonoModbusRtu (legacy) wordt gebruikt
exit status 1
Fout bij het compileren voor board Arduino/Genuino Uno

Could you perhaps suggest me which missing files I should be using?

**Comment by giampiero7** [comment]
Hi!
Yes, we recently split the library in different modules and the doc is still not updated. We'll fix it soon.
You need to install this lib too: https://github.com/sfera-labs/arduino-modbus-rtu-slave
