### ISSUE TITLE
Iono-Arduino not working with the Arduino Yun

### ISSUE THREAD

**Issue by operez06** [sfera-labs/iono#3]
Hello,

I uploaded  "iono/IonoWeb/examples/API/API.ino" to the Arduino Yun (this the arduino's model the Iono-Arduino had off the shelf).

I configured my Ethernet card to be in the same network as:

IP address: 192.168.1.245
Subnet mask: 255.255.255.0
Default gateway: 192.168.1.1

A simple ping command to 192.168.1.243 failed.

To troubleshoot the problem I connected an Arduino Uno with the Ethernet shield to the Iono-Arduino device and worked perfect.

Any idea please, why the Arduino Yun is not working?

Thanks

**Comment by giampiero7** [comment]
Hi,
The sketch is designed for Arduino Ethernet or WiFi.
The Yun needs its network configured on the Linux side.
I'll send you a sketch for the Yun.
