### ISSUE TITLE
Unable to use SoftwareSerial on Iono+Arduino yun rev 2

### ISSUE THREAD

**Issue by Ebrahim1604** [sfera-labs/iono#5]
Hello @giampiero7 , as highlighted in the following issue:
https://github.com/sfera-labs/iono/issues/4

I have decided to switch to Software Serial altogether to avoid using the Serial1 port of Yun.

I am using the pin 8 i.e. iono pin DO6 as Rx (since it is the only available pin which supports hardware interrupt) and the pin A3 i.e. Iono pin AI4 as the tx pin and attaching them to a ttl to usb converter to create a virtual COM port.

However, I'm unable to see any data on the virtual COM port for the following code, which is simply taken from the SoftwareSerial library example:
https://www.arduino.cc/en/Tutorial/LibraryExamples/SoftwareSerialExample

So, I'm guessing we cannot directly use iono pins as normal Arduino pins as they have relay contacts attached to them, am i correct?
![IMG-20210301-WA0001](https://user-images.githubusercontent.com/42499258/109472114-baf1ef00-7a97-11eb-87c9-79044206ef54.jpg)

In that case, what can be done to use the pins so that i could create a virtual Serial port using the SoftwareSerial library?

**Comment by giampiero7** [comment]
Hi,
No, you cannot use pins which are connected to specialized inputs or outputs.
If you need RS485, you can only use the TX/RX lines. If, on the other hand, you need TTL serial communication, you can use a soft serial on DI5/DI6 bypassed (move internal jumpers, see user guide).
