### ISSUE TITLE
ModbusRTUApp.ino missing reference FlashAsEEPROM.h

### ISSUE THREAD

**Issue by andhya** [sfera-labs/iono#7]
Library example does not compile;

`C:\Users\frank\Downloads\ModbusRtuApp\ModbusRtuApp.ino:19:10: fatal error: FlashAsEEPROM.h: No such file or directory
 #include <FlashAsEEPROM.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: FlashAsEEPROM.h: No such file or directory`

I've checked the dependencies listed in the wiki are installed;
[arduino-modbus-rtu-slave](https://github.com/sfera-labs/arduino-modbus-rtu-slave)
[arduino-wiegand](https://github.com/sfera-labs/arduino-wiegand)
[OneWire](https://www.arduino.cc/reference/en/libraries/onewire/)
[DallasTemperature](https://www.arduino.cc/reference/en/libraries/dallastemperature/)

but searching the arduino library directories doesn't find any results for a file called FlashAsEEPROM.h

**Comment by andhya** [comment]
Using Arduino IDE;
Version: 2.0.0
Date: 2022-09-14T07:06:37.759Z
CLI Version: 0.27.1 [a900cfb2]

and verifying for MKR Zero board

**Comment by andhya** [comment]
I've tried installing the FlashStorage library;
https://github.com/cmaglie/FlashStorage

but this raised another issue;
`In file included from C:\...\Arduino\libraries\iono-master\src\IonoModbusRtuSlave.cpp:32:0:
C:\...\Arduino\libraries\arduino-wiegand-master\src/Wiegand.h:16:10: fatal error: libs/wiegand-c-lib/wiegand.h: No such file or directory
 #include "libs/wiegand-c-lib/wiegand.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: exit status 1`

**Comment by giampiero7** [comment]
Hi @andhya ,
Thanks for the details.
For your initial issue, yes FlashStorage was the missing dependency.
It was recently added in the documentation here:
https://github.com/sfera-labs/iono/wiki/Modbus-RTU-Slave

The other issue is probably related to how you installed the arduino-wiegand library.
GitHub download does not support submodules, so you must download it using git, as specified in the doc:
https://github.com/sfera-labs/arduino-wiegand#readme

We are working on the riorganization of the libraries to make things smoother, thanks for your patience.

Let me know if this solves all issues.

Best,
Giampiero

**Comment by andhya** [comment]
Thanks @giampiero7 for the help so far; I've removed the ZIP-installed library and used the git method to install that instead, and the latest issue is;
```
CreateFile C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c: The file cannot be accessed by the system.

Compilation error: CreateFile C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c: The file cannot be accessed by the system.
```
I've checked that directory and the wiegand.c and wiegand.h files are 0KB and cannot be opened by a text editor. I've checked the git status in that folder and it's all up-to-date etc.

However, files of the same name exist at `Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib` which are 3KB and 2KB respectively and can both be opened by text editors and look superficially ok. I've tried copying these to the other subfolder but this results in many errors;

`C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\wiegand.c.o: In function `wiegandSetup':
C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib/wiegand.c:30: multiple definition of `wiegandSetup'
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c.o:C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand/wiegand.c:30: first defined here
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\wiegand.c.o: In function `wiegandGetData':
C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib/wiegand.c:37: multiple definition of `wiegandGetData'
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c.o:C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand/wiegand.c:37: first defined here
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\wiegand.c.o: In function `wiegandGetNoise':
C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib/wiegand.c:53: multiple definition of `wiegandGetNoise'
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c.o:C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand/wiegand.c:53: first defined here
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\wiegand.c.o: In function `wiegandOnData':
C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib/wiegand.c:60: multiple definition of `wiegandOnData'
C:\Users\frank\AppData\Local\Temp\arduino-sketch-8F3535B0DD13E500A19B46DFEFC0F135\libraries\arduino-wiegand\libs\wiegand-c-lib\examples\arduino\wiegand\wiegand.c.o:C:\Users\frank\Documents\Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand/wiegand.c:60: first defined here
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1`

Any suggestions as to what else I can try?

**Comment by andhya** [comment]
I deleted both the 0KB .h and .c files in `Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples\arduino\wiegand` and the sketch compiles ok - should I make this an issue on that repository instead?

**Comment by giampiero7** [comment]
Hi @andhya ,
Thanks for the report.
You can delete the whole `Arduino\libraries\arduino-wiegand\src\libs\wiegand-c-lib\examples` directory. 
The 0KB files are simply symbolic links to the other files, and it looks like they bother the Arduino IDE with the new library structure.
I'll have a look at it to fix it.
Thanks again,
Giampiero

**Comment by giampiero7** [comment]
@andhya I guess you gave me enough reasons to discard the submodules approach.
Now the arduino-wiegand repo contains a copy of the required files from wiegand-c-lib, so now you can simply download it from GitHub and the Arduino IDE does not complain.
Thanks for the push ;)
